# Build container
FROM keboolabot/webhooks-dev AS buildContainer

WORKDIR /go/src/app
COPY . .

RUN make generate-api
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -mod mod -ldflags "-s -w" -o /tmp/api ./cmd/api

# Production container
FROM alpine
RUN apk add -U --no-cache ca-certificates

COPY --from=buildContainer /tmp/api /app/api
WORKDIR /app

ENV HOST 0.0.0.0
ENV PORT 8000
EXPOSE 8000

CMD ["/app/api", "--http-host=0.0.0.0", "--http-port=8888"]
