version: '3'
services:
  dev:
    image: keboolabot/keboola-as-code-dev
    build: .
    volumes:
      - ./:/code:z
      - cache:/tmp/cache

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "8000:8000"
    environment:
      - KBC_STORAGE_API_HOST

volumes:
  cache:
