version: '3'
services:
  dev:
    image: keboolabot/webhooks-dev
    build: .
    volumes:
      - ./:/code:z
      - cache:/tmp/cache
    environment:
      - TEST_KBC_PROJECTS
      # OR
      - TEST_KBC_PROJECT_ID
      - TEST_KBC_STORAGE_API_HOST
      - TEST_KBC_STORAGE_API_TOKEN

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    depends_on:
      - dev
    ports:
      - "8888:8888"
    environment:
      - KBC_STORAGE_API_HOST

volumes:
  cache:
