version: '3'
services:
  dev:
    image: keboolabot/webhooks-dev
    build: .
    volumes:
      - ./:/code:z
      - cache:/tmp/cache

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    depends_on:
      - dev
    ports:
      - "8888:8888"
    environment:
      - KBC_STORAGE_API_HOST

volumes:
  cache:
